language: java
sudo: false
jdk:
- oraclejdk8
script:
- mvn clean verify install
after_success:
- cp target/ejbadass-log-plugin* ./ejbadass-log-plugin.jar
- cp target/maven-archiver/pom.properties .
deploy:
  provider: releases
  name: ejbadass-log-plugin
  tag_name: 1.1.0
  body: "Plugin to add logs to EJBadass project."
  draft: false
  api_key:
    secure: ELK8NFro2mj8zCJ6ofV5n9FhZsefUDlaUKJVPtqmgA82GLy3Yr+yuAvwhX2as75We72cHf1SW+bvA25PQff2qp/VXwIKv250M+g42Vjwn27gZ2CLfQ9MyIN7s8qRokRJ6GNhYqf58DW76K6kCF2Ylj3nhuG+SI2COSNFwyc3Nob2r5wZ5E2IrTezoYTI87nBto1ujXYQHK4zgL19Yv4eiCJJbemIp0jN4hLnrDLkz+B7e3Qsrqd6POZyXdW6OtabtjCwo0q4WVPynqiU5zL/RFwtFddqckKNpfayHMtFNUR+uXIoVsU9o7FaQgXA79xgcEgjuwftYTo4NXYNcifakWbhxS4dOPWgD15Cvhw30LlhUmn+svIDdDxZSB4DZpVKnbIl/PXOcApOnLAtnfcIFpWRlarvJowElkAKW5SYNzAPNkA4jVA6jCm6LOwSsWTIijqfOWFCwzcMAaoH/HSGQ8VBtp9U4IhSrLyZDttD4BS9wvzXTS4pZqiW2SwBV27JGL+yCed6vgWwLsh+k62+hyOxAh5E7hSYhVAAaxzN4vJdEJDLdNMrJpQvVmyknkx25q/6gV+92zFqDUmVRqynYzKnN94lyM1FVwqPiSJCHzNgypR/kTwd7XoXvxleuT6rWn2qVjhRS7EqYgTeBXkSAvM10KacnIh/zuBnBvbcfgs=
  file: 
   - ejbadass-log-plugin.jar
   - pom.properties
  overwrite: true
  skip_cleanup: true
  on:
    repo: EJBadass/ejbadass-log-plugin